created data models.
tahafurkanunsal/family-budget-app pull request #1
Opened 2022-12-25 15:03 UTC by tahafurkanunsal

2022-12-25 18:49 UTC, azizunsal requested changes
Degisiklik gerekli, spending entity'si istenilenleri tutmak icin yeterli degil.

2022-12-25 18:49 UTC, azizunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/model/Spending.java
> +    private int id;
1. `int` mi  `Integer` mi kullanilmali burada?
2. Tum alanlarda `spending...` seklinde bir isimlendirme yapmissin, gereksiz. Zaten spending entitysindesin, `id`'de oldugu gibi kullanilabilir.
3. `User` entitysi icin `id` taniminda `@GeneratedValue` var, burada neden yok? Kullanilmasi gerekmiyorsa orada neden kullaniyorsun?
4. `Category` bir `enum` olsun.

2022-12-25 18:49 UTC, azizunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/model/User.java
> +    private int id;
`int` mi `Integer` mi kullanilmali burada?

2022-12-26 21:34 UTC, azizunsal requested changes

2022-12-26 21:34 UTC, azizunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/model/Spending.java
> +}
`Category` yerine `SpendingType` adinda bir enum olsun, ve bunu yeni bir package(`enums`) altinda olustur.
Enum'in degerleri asagidakiler olabilir.
```
    GROCERY,
    BILLS,
    SCHOOL,
    HEALTH
```

Ayrica bir de `BillTypes` diye bir enum olusturmak lazim;
```
    WATER,
    ELECTRICITY,
    GAS
```
Seklinde degerleri olan.

2022-12-26 21:34 UTC, azizunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/model/Spending.java
> +    private String month;
`Mont` tarih tutmak icin yeterli degil, 2022 ve 2023'de yapilan harcamalar nasil tutulacak, month=Ocak dedin mesela?

2022-12-26 21:34 UTC, azizunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/model/User.java
> +    private List<Spending> spending;
List tipinde bir degisken tanimliyorsun birden fazla item var yani, `spending` degil `spendings`.

2022-12-26 21:34 UTC, azizunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/model/Spending.java
> +}
Mesela bir spending olsun ve tipi `Market`(=Grocery) olsun. Alt maddeleri nasil tutacaksin; cay aldin, seker aldin, deterjan vs.. aldin. Bunun icin detaylari tutan bir yapiya ihtiyacin var. Bir spending kaydi icin bir veya birden fazla olabilir.
```text
Spending { 
       - cay {id=1, price=55.0, description="cay"}
       - seker {id=2, price=30.0, description="cay sekeri"}
       - deterjan {id=3, price=100.0, description="makina deterjani"}
}
```

Type,  BILLS(=fatura), SCHOOL(=okul),HEALTH(=saglik)  ise bu detay kayda ihtiyac olmayacak.

2022-12-26 21:34 UTC, azizunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/FamilyBudgetAppApplication.java
Bu degisiklik gereksiz.

2022-12-26 21:38 UTC, azizunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/model/User.java
>      private String name;
`firstName`

2022-12-26 21:38 UTC, azizunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/model/User.java
>      private String lastname;
`lastName`

2022-12-26 21:47 UTC, azizunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/model/User.java
> +    private List<Spending> spending;
Ayrica bu iliskiyi burada degil, `Spending` tarafinda tanimla.

2022-12-28 08:04 UTC, azizunsal requested changes
Yorumlara gore degisiklikler gerekiyor.

2022-12-28 08:04 UTC, azizunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/model/SpendingDetails.java
> +@Table(name = "spending details")
Bu gecerli bir database table name degil, bosluk kullanamazsin. MySQL'de olusan tabloya baktin mi, select ile sorgu atmaya calisinca?

2022-12-28 08:04 UTC, azizunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/model/SpendingDetails.java
> +    private SpendingTypes spendingTypes;
Bu alan `Spending` tablosunda olacak, variable name olarak `type` yeterli.

2022-12-28 08:04 UTC, azizunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/model/SpendingDetails.java
> +    private BillTypes billTypes;
Bu alan Spending tablosunda olacak, var name `billingType`.

2022-12-28 08:04 UTC, azizunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/model/Spending.java
> +    private String date;
Date'i nasil tutacagina baktin ve bulamadin mi?
`java.util.Date` kullanacaksin.

2022-12-28 08:04 UTC, azizunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/model/SpendingDetails.java
> +public class SpendingDetails {
`SpendingDetail`

2022-12-28 08:04 UTC, azizunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/model/Spending.java
> +    private SpendingDetails spendingDetails;
https://github.com/tahafurkanunsal/family-budget-app/pull/1/files#r1057347906 buradaki yorumdan sonra bu iliskiyi one-to-one yapman dogru degil. Asagidaki sekilde olacak:
```java
    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)
    @JoinColumn(name = "spending_id")
    private List<SpendingDetail> details = new ArrayList<>();
```

2022-12-28 08:04 UTC, azizunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/enums/BillTypes.java
> +public enum BillTypes {
`BillingTypes` olarak degistir bunu, bir de aklina gelen diger fatura turlerini de yazabilirsin.

2022-12-28 08:04 UTC, azizunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/model/Spending.java
> +import tahafurkan.sandbox.familybudgetapp.repository.SpendingDetailsRepository;
Gonderilen kodda boyle bir class yok. Calismayan / hatali  kodu PR icin gonderme.

2022-12-28 08:04 UTC, azizunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/model/Spending.java
> +    private double amount;
`amount` neyi ifade ediyor, fiyat mi yoksa miktar mi? Miktar ise ben kullanimini nasil olacak anlamadim(aciklayabilirsin), fiyat ise eger, asagidaki tabloda `price` demissin, ayni olsun.

2022-12-28 09:11 UTC, tahafurkanunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/model/SpendingDetails.java
> +    private SpendingTypes spendingTypes;
tamam düzeltiyorum.

2022-12-28 09:12 UTC, tahafurkanunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/model/SpendingDetails.java
> +    private BillTypes billTypes;
düzeltiyorum

2022-12-28 09:12 UTC, tahafurkanunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/model/Spending.java
> +    private String date;
Buldum aslında düzeltmeyi bu atmış oldugum son commit de yapıcaktım unutmusum.

2022-12-28 09:15 UTC, tahafurkanunsal commented on src/main/java/tahafurkan/sandbox/familybudgetapp/model/Spending.java
> +    private double amount;
toplam fiyat olarak düşünmüştüm , girilen spending'lerin price'larının toplamı yazılabilir diye.

2022-12-28 12:11 UTC, azizunsal approved these changes

2022-12-28 12:11 UTC, merged